"""Generate `case/cases/distribution/case459_0.py` from the SwissDN parquets.

The tables are embedded in the generated module rather than read from
`data/parquet/` at run time, because `powermarketjax/case/` is self-contained
today -- no case file reads `data/` -- and opening that coupling for one case is
not worth it.  The cost is that the same numbers live in the repository twice,
and a generator alone does not pay it: nobody runs a generator.  What pays it is
`tests/data/test_case459_0_is_regenerable.py`, which regenerates the module and
asserts it is byte-identical to the committed one.  The docstring records where
the numbers came from; that test is the link that breaks when they diverge.

    PYTHONPATH=<repo> python tools/case_audit/generate_case459_0.py --check
    PYTHONPATH=<repo> python tools/case_audit/generate_case459_0.py --write
"""
import argparse
import math
from pathlib import Path

import pandas as pd

import powermarketjax

REPO = Path(powermarketjax.__file__).resolve().parents[1]
PQ = REPO / "powermarketjax/data/parquet"
TARGET = REPO / "powermarketjax/case/cases/distribution/case459_0.py"

BASE_KV = 20.0
BASE_MVA = 100.0
POWER_FACTOR = 0.9


def _rows(frame, cols):
    return "\n".join("        [" + ", ".join(repr(v) for v in row) + "],"
                     for row in frame[cols].itertuples(index=False))


def render() -> str:
    nodes = pd.read_parquet(PQ / "SwissDN_459_0_MV_Nodes.parquet")
    edges = pd.read_parquet(PQ / "SwissDN_459_0_MV_Edges.parquet")

    osmid = nodes["osmid"].astype(str).tolist()
    index = {o: i + 1 for i, o in enumerate(osmid)}       # 1-based bus ids
    slack_osmid = str(nodes.loc[nodes["source"], "osmid"].iloc[0])
    z_base = BASE_KV ** 2 / BASE_MVA
    tan_phi = math.tan(math.acos(POWER_FACTOR))

    n = pd.DataFrame({
        "id": [index[o] for o in osmid],
        "type": [3 if o == slack_osmid else 1 for o in osmid],
        "Pd": nodes["peak_mw"].astype(float).round(9),
        "Qd": (nodes["peak_mw"].astype(float) * tan_phi).round(9),
        "x": nodes["coord_e_m"].astype(float),
        "y": nodes["coord_n_m"].astype(float)})
    e = pd.DataFrame({
        "id": range(1, len(edges) + 1),
        "from": [index[str(u)] for u in edges["u"]],
        "to": [index[str(v)] for v in edges["v"]],
        "r": (edges["r_ohm"].astype(float) / z_base).round(12),
        "x": (edges["x_ohm"].astype(float) / z_base).round(12),
        "status": 1,
        "floor": -1e6,
        "cap": edges["s_nom_mva"].astype(float)})
    ld = pd.DataFrame({
        "id": range(1, len(nodes) + 1),
        "bus_id": [index[o] for o in osmid],
        "d_max": nodes["peak_mw"].astype(float).round(9),
        "d_min": nodes["peak_mw"].astype(float).round(9)})
    base_v = ", ".join(repr(round(float(v), 12))
                       for v in nodes["base_case_voltage_pu"])

    return f'''# Generated by tools/case_audit/generate_case459_0.py -- do not hand-edit.
# `tests/data/test_case459_0_is_regenerable.py` regenerates this file from the
# parquets and asserts it is byte-identical, so an edit here fails there.
"""Case459_0: SwissDN medium-voltage feeder 459_0 (Geneva).

Grid type: distribution, radial
{len(nodes)} buses, 0 generators, {len(edges)} branches, {len(nodes)} loads
Base MVA: {BASE_MVA} | Base kV: {BASE_KV}

Source: SwissDN, Zenodo record 15056134, CC BY 4.0 (cleared with the parquets).
Generated from `SwissDN_459_0_MV_Nodes.parquet` and `SwissDN_459_0_MV_Edges.parquet`
by `tools/case_audit/generate_case459_0.py`.

**The voltage band is not part of this case and has no default.**  The source
does not supply per-bus limits -- every other vendored case here does -- so
`create_case459_0` takes `node_v_min` and `node_v_max` as required keywords and
`load_case("459_0")` raises rather than inventing a band.  §18 carries the
decision.  A band that merely lets the market run is the failure mode being
prevented: the European standard's +-10% is twice the main case's registered
width, and a wider band moves the scale factor at which voltage requirements
appear, so adopting it requires recalibrating that factor rather than carrying
it across.

**Four things are declared here rather than read from the source.**

`base_mva = {BASE_MVA}` -- the *choice* of base is free, because the voltage
solution is invariant to it: r_pu * p_pu = r_ohm * p_mw / base_kv^2, so the base
cancels when r, x and the loads are all expressed on the same one.  It is
therefore **not** pinned by the base-case reproduction below.  But `_LINES`
already carries r and x per-unit **on this base**, so the two are no longer
independent once generated: `create_case459_0` takes no `base_mva` argument,
because changing it without rescaling r and x would silently produce an
inconsistent case.  A different base means regenerating.

`status = 1` on every branch -- the source records no tie switches and the
feeder is radial, so all-in-service is the only self-consistent reading.

`Qd = Pd * tan(arccos(0.9))` -- the source carries no reactive power.  0.9 is
what the Nodes sidecar derives from the data, as the **minimum** of
downstream_peak_mw / (base_case_flow * s_nom_mva), reached on the most heavily
loaded edges.  It is therefore a lower bound by construction, not an estimate,
and the measured consequence is that this case sits **systematically below** the
published base case by at most 4.69e-4 p.u., one-sided across all buses (128
low, 0 high, correlation -0.995 with the voltage drop) -- the shape of slightly
too much reactive load.  A power factor near 0.92 fits the base case better
(1.59e-4) and **is deliberately not used**: fitting it to the published solution
would spend the one independent check this dataset ships, turning the base case
from a validation target into a fitting target.  A second candidate for the same
residual is line charging, which the source carries as `b_siemens` and the BFS
does not model at all; it points the same way and is **untested**, so it is not
excluded.

`slack_bus_idx` -- the single node with `source = True` (osmid {slack_osmid}).

**`Pd` is the nodal PEAK**, so this case is the peak-loading snapshot.  The
hourly series is a separate dataset (`swissdn_459_0_mv_load`, keyed by osmid):
the case supplies the network, the series supplies time, as in §14 for the
Australian configuration.

`b_siemens` from the source is deliberately **not** carried into `line_b`: it
would need a per-unit conversion that nothing here validates, and no consumer
reads it.  It remains in the parquet.
"""

from powermarketjax.case.case_builder import build_case_from_tables
from powermarketjax.case.case_data import CaseData

#: The source's own power-flow solution, per bus, in the order of `_NODES`.
#: Kept as the validation target for the BFS check, not as case input.
BASE_CASE_VOLTAGE_PU = ({base_v},)

#: EN 50160's supply-voltage variation for medium voltage, as a pair a caller can
#: pass to `create_case459_0`.  **Naming them is not defaulting to them**: the
#: factory still requires both arguments, so a run always records which band it
#: used.  `base_kv = {BASE_KV}` puts this feeder in the standard's MV class
#: (1 kV < Un <= 36 kV), where it gives Uc +-10%.
#:
#: **Using it as (VLO)/(VHI) is a modelling choice, not a citation, and it
#: departs from the standard in both directions at once.**  Tighter: the standard
#: is a statistical criterion -- 95% of the 10-minute means over a week -- while
#: §6 applies the band as a hard bound in every period, i.e. at 100%.  Looser:
#: +-10% is a wider band than the 0.95 lower limit this market's calibration
#: previously assumed, and a wider band moves the load scale at which voltage
#: requirements appear, so any factor calibrated against the old width has to be
#: recalibrated rather than carried across.  Reporting only the first direction
#: would suggest the choice is uniformly conservative; it is not.
EN50160_MV_V_MIN = 0.9
EN50160_MV_V_MAX = 1.1

_NODES = [
    {list(n.columns)!r},
{_rows(n, list(n.columns))}
]

#: No generators: this feeder's only infeed is the substation, which is the
#: slack bus.  The market's batteries are participants, not case units.
_UNITS = [
    ["id", "bus_id", "mc_a", "mc_b", "mc_c", "p_max", "p_min"],
]

_LINES = [
    {list(e.columns)!r},
{_rows(e, list(e.columns))}
]

_LOADS = [
    {list(ld.columns)!r},
{_rows(ld, list(ld.columns))}
]


def create_case459_0(*, node_v_min: float, node_v_max: float) -> CaseData:
    """Build feeder 459_0 with an explicitly declared voltage band.

    Args:
        node_v_min: Lower voltage limit [p.u.], applied to every bus.  Required:
            the source supplies none and the local flexibility market has not settled one.
        node_v_max: Upper voltage limit [p.u.], applied to every bus.

    There is deliberately no `base_mva` argument; see the module docstring.
    """
    nodes_cols = _NODES[0] + ["Vmin", "Vmax"]
    nodes_data = [row + [node_v_min, node_v_max] for row in _NODES[1:]]
    return build_case_from_tables(
        nodes_cols=nodes_cols, nodes_data=nodes_data,
        units_cols=_UNITS[0], units_data=_UNITS[1:],
        lines_cols=_LINES[0], lines_data=_LINES[1:],
        loads_cols=_LOADS[0], loads_data=_LOADS[1:],
        base_mva={BASE_MVA},
    )


def _voltage_band_undeclared() -> CaseData:
    """Registry entry for 459_0: raises, because the band is undeclared.

    This is a temporary shape, not this case's design.  Once §18 settles a band
    the constants go in here and this becomes an ordinary zero-argument factory
    identical to the other twelve.
    """
    raise ValueError(
        "case '459_0' has no registered voltage band: the SwissDN source "
        "supplies no per-bus voltage limits, and the local flexibility market "
        "has not settled one.  A default would let "
        "the market produce numbers on an uncalibrated band, so there is none.  "
        "Call create_case459_0(node_v_min=..., node_v_max=...) with an explicit "
        "band.  When §18 settles, those constants move into this factory and it "
        "becomes an ordinary zero-argument one like every other case.")
'''


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.write:
        TARGET.parent.mkdir(parents=True, exist_ok=True)
        TARGET.write_text(text)
        print(f"wrote {TARGET} ({len(text)} bytes)")
    elif args.check:
        same = TARGET.exists() and TARGET.read_text() == text
        print(f"{'identical' if same else 'DIFFERS'}: {TARGET}")
    else:
        print(text[:2000])


if __name__ == "__main__":
    print(f"powermarketjax.__file__ = {powermarketjax.__file__}")
    main()
